# Generated by Django 2.0.9 on 2020-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=40)),
                ('modified_image', models.ImageField(blank=True, null=True, upload_to='modified_images/')),
            ],
        ),
    ]
