# Generated by Django 2.0.9 on 2020-05-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_opencv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
